

APP_NAME: WikitoFile Local
APP_ID: local-1476988010946
MASTER_URL: local[*]
UTC: 2016-10-20 18:26:49.158338

Traceback (most recent call last):
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/teste.py", line 72, in <module>
    main(sc)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/teste.py", line 49, in main
    ftest=open(test.json,"a+")
NameError: global name 'test' is not defined


APP_NAME: WikitoFile Local
APP_ID: local-1476988021793
MASTER_URL: local[*]
UTC: 2016-10-20 18:27:00.309115

Traceback (most recent call last):
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/teste.py", line 72, in <module>
    main(sc)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/teste.py", line 49, in main
    ftest=open(test.json,"a+")
NameError: global name 'test' is not defined


APP_NAME: WikitoFile Local
APP_ID: local-1476988049119
MASTER_URL: local[*]
UTC: 2016-10-20 18:27:27.705639



APP_NAME: WikitoFile Local
APP_ID: local-1476988133512
MASTER_URL: local[*]
UTC: 2016-10-20 18:28:52.111817



APP_NAME: WikitoFile Local
APP_ID: local-1476988241786
MASTER_URL: local[*]
UTC: 2016-10-20 18:30:40.287870



APP_NAME: WikitoFile Local
APP_ID: local-1476989284023
MASTER_URL: local[*]
UTC: 2016-10-20 18:48:02.647654

descriptor 'isoformat' requires a 'datetime.datetime' object but received a 'str'
Traceback (most recent call last):
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/teste.py", line 80, in <module>
    main(sc)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/teste.py", line 58, in main
    fjson.close()
UnboundLocalError: local variable 'fjson' referenced before assignment


APP_NAME: WikitoFile Local
APP_ID: local-1476989414853
MASTER_URL: local[*]
UTC: 2016-10-20 18:50:13.443831

global name 'ftest' is not defined


APP_NAME: WikitoFile Local
APP_ID: local-1476989803579
MASTER_URL: local[*]
UTC: 2016-10-20 18:56:42.127119



APP_NAME: WikitoFile Local
APP_ID: local-1476991459599
MASTER_URL: local[*]
UTC: 2016-10-20 19:24:18.000555



APP_NAME: WikitoFile Local
APP_ID: app-20161022021016-0001
MASTER_URL: spark://143.106.73.43:7077
UTC: 2016-10-22 02:10:45.640547

Page id "burg khong long" does not match any pages. Try another id!
u'url'
/usr/local/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 774 of the file /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
"Wroxall" may refer to: 
Wroxall, Isle of Wight
Wroxall, Warwickshire
Page id "nam tok tat kinnaird" does not match any pages. Try another id!
"Gwyn" may refer to: 
Gwyn (name)
Gwynne, Alberta
Gwynn, Virginia
Gwynn Oak, Maryland
Gwynn's Island
Gwynneville, New South Wales
Bryn Gwyn stones
Castell Bryn Gwyn
Hendy-gwyn
Gwynn (Sluggy Freelance)
Dark Souls
Gwynn Park High School
St Richard Gwyn Roman Catholic High School (disambiguation)
Gwyn ap Nudd
Nell Gwyn (disambiguation)
Nell Gwyn Stakes
Ty Gwyn (disambiguation)
u'links'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 107, in getPages
    dictsToJson(wikidict,linkdict,language)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 113, in dictsToJson
    dTJcounter +=1
UnboundLocalError: local variable 'dTJcounter' referenced before assignment

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 107, in getPages
    dictsToJson(wikidict,linkdict,language)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 113, in dictsToJson
    dTJcounter +=1
UnboundLocalError: local variable 'dTJcounter' referenced before assignment

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 107, in getPages
    dictsToJson(wikidict,linkdict,language)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 113, in dictsToJson
    dTJcounter +=1
UnboundLocalError: local variable 'dTJcounter' referenced before assignment

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 107, in getPages
    dictsToJson(wikidict,linkdict,language)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 113, in dictsToJson
    dTJcounter +=1
UnboundLocalError: local variable 'dTJcounter' referenced before assignment



APP_NAME: WikitoFile Local
APP_ID: app-20161022022903-0002
MASTER_URL: spark://143.106.73.43:7077
UTC: 2016-10-22 02:29:31.887222

/usr/local/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 774 of the file /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
"hradec" may refer to: 
Hradec Králové
Hradec Králové Region
Hradec nad Moravicí
Jindřichův Hradec
Levý Hradec
Hradec substation
Hradec (Havlíčkův Brod District)
Hradec (Plzeň-South District)
Hradec (Prievidza)
Graz
"Phlox (disambiguation)" may refer to: 
USS Phlox (1864)
Phlox (Star Trek)
Phlox, Indiana
Phlox, Wisconsin
u'url'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 106, in getPages
    dictsToJson(wikidict,linkdict,language)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 112, in dictsToJson
    DTJ_COUNTER +=1
UnboundLocalError: local variable 'DTJ_COUNTER' referenced before assignment

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 106, in getPages
    dictsToJson(wikidict,linkdict,language)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 112, in dictsToJson
    DTJ_COUNTER +=1
UnboundLocalError: local variable 'DTJ_COUNTER' referenced before assignment

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 106, in getPages
    dictsToJson(wikidict,linkdict,language)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 112, in dictsToJson
    DTJ_COUNTER +=1
UnboundLocalError: local variable 'DTJ_COUNTER' referenced before assignment

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 106, in getPages
    dictsToJson(wikidict,linkdict,language)
  File "/Users/ederalcazar/Documents/Repositories/mc855/projeto2/wtf.py", line 112, in dictsToJson
    DTJ_COUNTER +=1
UnboundLocalError: local variable 'DTJ_COUNTER' referenced before assignment

